### ISSUE TITLE
Add component for page sections with full backgrounds (homepage 2nd section)

### ISSUE THREAD

**Issue by StudioSpindle** [SeMI-network/semi-website#122]

**Comment by StudioSpindle** [comment]
note: requires big refactor of page setup because of full background width

**Comment by bobvanluijt** [comment]
Does that bring any issues to your estimations @StudioSpindle ?

**Comment by StudioSpindle** [comment]
It might.

**Comment by bobvanluijt** [comment]
@michaverhagen CC

**Comment by StudioSpindle** [comment]
Yes, I'll notify Micha if anything changes regarding estimates.

**Comment by StudioSpindle** [comment]
Adding a 'container' and 'wrapper' option to use within the site. 

The container class will add the gutter on each side of the page.
The wrapper class will center the column.

**Drawback:** this will add to the HTML 'weight'. Every section of the page will have to have an additional class (for the container), and inside that, all the containers will have an additional div (with the wrapper class). 

**Advantage(s):** you can now use full-width background sections, and that it's a reusable pattern. You can simply now create centered columns by adding this. Also, it's recognizable in the code. If you'd, for example, use the existing classes to add the CSS properties for the same technique, it would be hard to recognize where it has been applied since it will be intertwined in the code.

**Comment by StudioSpindle** [comment]
Added container and wrapper layout example to styleguide:

<img width="1431" alt="screen shot 2018-09-16 at 13 38 26" src="https://user-images.githubusercontent.com/9882035/45596045-de9f4880-b9b5-11e8-9976-3b00af94eb2c.png">
