### ISSUE TITLE
Run through application and even out component en section spacings (milestone 2)

### ISSUE THREAD

**Issue by StudioSpindle** [SeMI-network/semi-website#134]

**Comment by bobvanluijt** [comment]
@StudioSpindle : https://github.com/SeMI-network/semi-website/issues/138

**Comment by rafaelcanalesduron** [comment]
@StudioSpindle can we add here the spacings mentioned in the document?
https://docs.google.com/document/d/1z-baq1MzyovFM2VQ-5viAAiSeIH_yR1UEazrHEndOZI/edit?ts=5b9fd42a

**Comment by StudioSpindle** [comment]
example page: https://www.semi.network/products/weaviate-enterprise.html

<img width="984" alt="screenshot 2019-01-31 at 10 19 51" src="https://user-images.githubusercontent.com/9882035/52044180-ca617f80-2541-11e9-84be-44a3a14d875c.png">

**Comment by StudioSpindle** [comment]
closed in favor of #241
