### ISSUE TITLE
Memory issue homepage

### ISSUE THREAD

**Issue by bobvanluijt** [SeMI-network/semi-website#138]
Something is eating a lot of memory on the homepage (only the hompage). FF and Chrome sometimes have a hard time rendering and IE is sometimes crashing.

**Comment by StudioSpindle** [comment]
Steps to reproduce? Just opening a browser? :P

**Comment by bobvanluijt** [comment]
Haha, yes

**Comment by bobvanluijt** [comment]
It is _something_ that the homepage has and others don't.
