### ISSUE TITLE
Add icons, graphics and infographics to styleguide

### ISSUE THREAD

**Issue by StudioSpindle** [SeMI-network/semi-website#141]
t.b.d.

**Comment by rafaelcanalesduron** [comment]
https://docs.google.com/document/d/1X_fgtNYIlV0b-fe5Fyp_m3obetMQ55HbTmlWcqL02kQ/edit?usp=sharing 

Started a document with descriptions for 'graphic elements'.

**Comment by StudioSpindle** [comment]
@rafaelcanalesduron Can you create the two icon libraries as a zip file?

**Comment by StudioSpindle** [comment]
@rafaelcanalesduron It's becoming quite a large page. Would it perhaps be an idea that we cut it up into smaller more manageable sub-pages?

**Comment by StudioSpindle** [comment]
@rafaelcanalesduron Can you provide the svg's for all the _business verticals_?

**Comment by StudioSpindle** [comment]
@rafaelcanalesduron There seem to be some discrepancies in the icons. For example between the icons for engineering on the white and dark background. I will just use the existing ones. 

If the page is finished maybe you can then see if some will have to be replaced.

**Comment by rafaelcanalesduron** [comment]
@StudioSpindle I've added the SVGs for the verticals in Zeplin.

And here are the links to the icons zips:
PNG: https://drive.google.com/file/d/1x1cDY2xaZy4Y8vd7bqmQytaH5iD7DvNR/view
SVG: https://drive.google.com/file/d/1bEbyv2eZSaKVlsoZO8gQBkmCa2YfRxZP/view
