### ISSUE TITLE
Some text style corrections

### ISSUE THREAD

**Issue by rafaelcanalesduron** [SeMI-network/semi-website#153]
The styles can be found in [zeplin](zpl://project?pid=5b7e6c6c20f52a2034f91e93)

The ones to correct are the 'Section Title' and to add a 'Page title' style.
![image](https://user-images.githubusercontent.com/41619961/45889439-c158e880-bdc0-11e8-84e0-1256ff498561.png)

**Comment by bobvanluijt** [comment]
@rafaelcanalesduron you have a bit more context here? What why and how?

**Comment by rafaelcanalesduron** [comment]
The text styles were not implemented as in the design documentation. I'd like to implement them as in the design for consistency and to be able to highlight certain elements in a page to help people navigate the content more easily:
zpl://project?pid=5b7e6c6c20f52a2034f91e93
https://zpl.io/VknR8mv 

![image](https://user-images.githubusercontent.com/41619961/45942111-71a53780-bfe1-11e8-8387-0892de1fef52.png)
![image](https://user-images.githubusercontent.com/41619961/45942128-7ff35380-bfe1-11e8-9d9c-e54a0ac64298.png)

I think it would require only to change the definition of the text styles in the CSS file.
