### ISSUE TITLE
Add downloadable options to graphics

### ISSUE THREAD

**Issue by StudioSpindle** [SeMI-network/semi-website#157]
Page `styleguide/style-graphic-iconography.html`
Add a .zip file with all the PNG's as downloadable options.
Add a .zip file with all the SVG's as downloadable options.

Page `styleguide/style-graphic-playground.html`
Add the PNG's as downloadable options.

**Comment by StudioSpindle** [comment]
Hey @rafaelcanalesduron ,

Can you provide me with two .zip files with the icons. 
1. Every icon as regular .png, @2x.png and @3x.png.
2. Every icon as .svg.

As a reminder: It would be for the downloadable options on this page: 

![screenshot 2018-10-19 at 13 59 06](https://user-images.githubusercontent.com/9882035/47217062-68707600-d3a7-11e8-83f9-29e8afe0cbf8.png)

**Comment by rafaelcanalesduron** [comment]
Here are the icons:
[icons-library-svg-27-09-2018.zip](https://github.com/SeMI-network/semi-website/files/2589157/icons-library-svg-27-09-2018.zip)

[icons-library-png-06-08-2018.zip](https://github.com/SeMI-network/semi-website/files/2589158/icons-library-png-06-08-2018.zip)
