### ISSUE TITLE
Logo in navigation bars with white-background is also white (not visible)

### ISSUE THREAD

**Issue by rafaelcanalesduron** [SeMI-network/semi-website#168]

**Comment by StudioSpindle** [comment]
Hi @rafaelcanalesduron, do you have some URL's with this bug ocurring?

**Comment by rafaelcanalesduron** [comment]
Yes,
http://dev.semi.network/products/
![image](https://user-images.githubusercontent.com/41619961/48619616-5c270b00-e99d-11e8-8a2a-d154e0e1c2ec.png)
