### ISSUE TITLE
tags page has text aligning to the left of the window

### ISSUE THREAD

**Issue by StudioSpindle** [SeMI-network/semi-website#169]
See: https://www.semi.network/tags/technology/

The container and wrapper div's are missing.

**Comment by bobvanluijt** [comment]
Can you help with this @StudioSpindle or can I do this?

**Comment by StudioSpindle** [comment]
@bobvanluijt I will be picking this up as I'm starting with this entire knowledge section.

**Comment by bobvanluijt** [comment]
Awesome
