### ISSUE TITLE
Blog template – side navigation, tags as categories (list)

### ISSUE THREAD

**Issue by rafaelcanalesduron** [SeMI-network/semi-website#176]
Creating categories for the side navigation from tags in blog posts/articles.

**Comment by StudioSpindle** [comment]
New BE component. A list of the tags that are available.

**Comment by rafaelcanalesduron** [comment]
![image](https://user-images.githubusercontent.com/41619961/52044962-b1f26480-2543-11e9-99f1-8d5d9acc2a91.png)

![image](https://user-images.githubusercontent.com/41619961/52044982-c0d91700-2543-11e9-83b3-fba9a989c3a5.png)

**Comment by StudioSpindle** [comment]
Not relevant anymore
