### ISSUE TITLE
Blog template – Index page with ‘latest’ posts

### ISSUE THREAD

**Issue by rafaelcanalesduron** [SeMI-network/semi-website#177]

**Comment by rafaelcanalesduron** [comment]
![image](https://user-images.githubusercontent.com/41619961/52045052-f1b94c00-2543-11e9-8012-b8a3d30ccad7.png)

**Comment by StudioSpindle** [comment]
Is this ticket still relevant? Since @bobvanluijt requested to keep it flat and land on the executive summary directly.

@rafaelcanalesduron please close or reassign this issue depending on the action.
