### ISSUE TITLE
Width of the body doesn't correspond with the design

### ISSUE THREAD

**Issue by StudioSpindle** [SeMI-network/semi-website#190]
The default width of the page in the front-end isn't as wide as the default width of the page in the designs. This is most evident when looking at the article pages, where a sidebar resides next to the bodycopy.

Example of the front-end:

<img width="1241" alt="screenshot 2018-11-25 at 19 47 28" src="https://user-images.githubusercontent.com/9882035/48983110-27c4f480-f0eb-11e8-825c-249afdb82679.png">

Example of the design: 

<img width="982" alt="screenshot 2018-11-25 at 19 50 03" src="https://user-images.githubusercontent.com/9882035/48983127-55aa3900-f0eb-11e8-8a50-cc2b5b71954c.png">

**Comment by StudioSpindle** [comment]
@rafaelcanalesduron What shall we do here, widen the default body wrapper of the front-end? That would mean that the cards on the homepage would also become wider.

**Comment by rafaelcanalesduron** [comment]
@StudioSpindle Let's leave it as it is, the important thing is the text is readable and we keep consistency with the rest.
