### ISSUE TITLE
Additional formatting for topic detail page

### ISSUE THREAD

**Issue by StudioSpindle** [SeMI-network/semi-website#191]
The knowledge pages are divided into the following structure:

_Topics_: 
- "wiki-weaviate"
- "wiki-semi-consulting"

Both of these topics have these _categories_:
- "learn"
- "implement"
- "start"

Then the structure follows this path. 

---
1. Click on "knowledge base" in the menu. Then you'll land on the **(KB-A) knowledge base topic overview page.**: 

![screencapture-127-0-0-1-4000-knowledge-base-2018-11-25-21_05_37](https://user-images.githubusercontent.com/9882035/48983960-e71ea880-f0f5-11e8-8482-1dfa22801716.png)
---
2. Clicking on either one of these two topics "Learn more" button, you'll land on the **(KB-B) category overview page** for the corresponding topic:

![screencapture-127-0-0-1-4000-knowledge-base-wiki-semi-consulting-2018-11-25-21_09_01](https://user-images.githubusercontent.com/9882035/48983994-5f856980-f0f6-11e8-90d9-a5d473362106.png)
![screencapture-127-0-0-1-4000-knowledge-base-wiki-weaviate-2018-11-25-21_08_45](https://user-images.githubusercontent.com/9882035/48983995-5f856980-f0f6-11e8-98f8-64ae7f452f99.png)
---
3. Once you click on either one of the links in the _category link blocks_, you'll land on the **(KB-C) knowledge base article detailpage**:

![screencapture-127-0-0-1-4000-knowledge-base-wiki-weaviate-learn-executive-summary-2018-11-25-21_10_23](https://user-images.githubusercontent.com/9882035/48984008-8d6aae00-f0f6-11e8-83ec-6f15fd3f4091.png)

**Comment by rafaelcanalesduron** [comment]
@StudioSpindle We can eliminate step 2. In step 1 when you click on learn more, you could directly go to the first topic in the knowledge base. So from KB-A you go directly to KB-C (on the first available topic).

Question, can the categories be modified (e.g. remove some/add more, and change their names)?
