### ISSUE TITLE
Add new front-matter fields to articles

### ISSUE THREAD

**Issue by StudioSpindle** [SeMI-network/semi-website#197]
New fields:
```
author:
date_first_published:
```

**Comment by rafaelcanalesduron** [comment]
In the design for blog pages we defined this as shown below:
![image](https://user-images.githubusercontent.com/41619961/52046106-380faa80-2546-11e9-8594-f106592ff104.png)

**Comment by StudioSpindle** [comment]
My action: Add to the template HTML for both the blog pages and the knowledge base. If the info isn't filled in then it isn't shown. Once that is in place, notify @carne-vore that it's ready and James can start populating the desired pages with the corresponding author/date.

**Comment by carne-vore** [comment]
I thought that Github knows both bits of info anyway - so it can populate automatically from the GH info - no?
WHich brings me to part B - even if manual it should be consistent so there should be a micro-PeopleDatabase with our names, display names, and titles - that way as they change the data will also change.
Say Bob wants te be called "CEO" not "Founder" we should not have to Search/Replace in every document. 
It should be a very simple thing with a unique ID for everyone (their GH ID?) and then their details as held internally and as they should be displayed

**Comment by rafaelcanalesduron** [comment]
I agree with James on semi-automating it and having a database of authors. This would be very useful in the future as we make changes to the KB.

For who is the author, there might be cases where someone else makes changes on GitHub on behalf of the author, so that can be manually defined.

**Comment by carne-vore** [comment]
who can create that database? it is really just a few rows and columns - I can give a design (it needs to be extensible as well, we will not be 100% right first release)

**Comment by StudioSpindle** [comment]
@rafaelcanalesduron @carne-vore created a working example. You can find it in this branch: https://github.com/SeMI-network/semi-website/tree/feature/gh-197-page-authors

2 things aren't possible: Automatically populating via Github information, and adding a "database".

However, as you will see in the files there is a JSON file in which you can add the data. It's in:
`./_data/authors.yml`. Can you perhaps populate this? 

The way that it works is that on page level, in the front-matter you give the following two fields:
```
author: bob
pubdate: january 14, 2019
```
You can see this example in `./knowledge-base/wiki-semi-consulting/learn/executive-summary/index.md` line *12-13*.

Then what this in the layout template does, is it will look for the author 'bob' in the previously mentioned authors YML file. If that exists it will display both the field 'displayname' and 'title'.

**Comment by StudioSpindle** [comment]
In the design it's visible that the author has a line underneath it suggesting it's a link to a _author detail page_. What I suggest is that we will first create those pages. We are free to populate these pages in any way we would like to using HTML.

Then once they're done, we can add a line in the authors.yml file. This line will contain the URL of the author. I will then update the layout file and add the anchor link there and voila, it will be linked to an author page.

Thoughts?

**Comment by rafaelcanalesduron** [comment]
@StudioSpindle The idea is not to go to an author detail page, but an 'index' page listing all the articles published by that author, similar to what you would see if you ran a search.
https://zpl.io/bPvXXNm

**Comment by carne-vore** [comment]
Could we combine both - you arrive at a list of their articles but the top contains a smal bio of the author whihc could be held in the same json file

bob:
    displayname: Bob v. Luijt
    title: Founder of SeMI
    bio: Started life as an embryo and matured through X and Y to currently being Z
and only call that bio data on the results page?

**Comment by carne-vore** [comment]
I like this - it is all driven by having ``author: bob`` in the header?
Is there a way to have an anonymous or multi-author - I guess we could deal with that by having a special case name like "nobody" which would have an entry in the json like
 
nobody:
displayname: SeMI
title:

**Comment by carne-vore** [comment]
is this possible @StudioSpindle ? see comment above

**Comment by StudioSpindle** [comment]
The date is added.

Yes it is possible to add a bio. Changes for author pages are in PR: https://github.com/SeMI-network/semi-website/pull/294

The JSON doesn't have to be updated anymore since it has been replaced with actual pages under `./_authors/**`. These pages are automatically indexed and can be used for blog articles. 

An author must have a key, and the blogpost will have to have a reference to that key as well in the Jekyll front-matter (top part of .md file). Then it will automatically pick up those fields. See for the example the autor pages I've already created.

We can add a "nobody" account, but you could also just leave it empty? 

Closing this issue in the PR, please raise a new one if you need a specific new 'nobody' author.
