### ISSUE TITLE
add box to emphasize product type in features 

### ISSUE THREAD

**Issue by carne-vore** [SeMI-network/semi-website#230]
@StudioSpindle can you make the product referred to clearer on the Features.yml file so that on white label the column is boxed (or whatever you chose) and on enterprise that column is boxed (or whatever)?

**Comment by carne-vore** [comment]
![image](https://user-images.githubusercontent.com/45226724/50347635-88065500-0536-11e9-93cf-0cd0917ee2d0.png)

**Comment by StudioSpindle** [comment]
@rafaelcanalesduron can you provide a design please?

**Comment by rafaelcanalesduron** [comment]
![image](https://user-images.githubusercontent.com/41619961/52574350-629e1500-2e1c-11e9-9e0f-db6f08a1d14c.png)
Zeplin reference: https://zpl.io/aBylvYm

Additionally, can the column headers for W OS, W Enterprise and W White-Label be centered?
