### ISSUE TITLE
Try to have the slogan is 1 line

### ISSUE THREAD

**Issue by bobvanluijt** [SeMI-network/semi-website#232]
`Your data becomes your knowledge`

Now it breaks the line often after "knowledge".

<img width="488" alt="screenshot 2018-12-21 at 16 56 21" src="https://user-images.githubusercontent.com/5509162/50351141-8aba7780-0541-11e9-858a-e107411c1036.png">

**Comment by StudioSpindle** [comment]
<img width="745" alt="medium" src="https://user-images.githubusercontent.com/9882035/50400284-d1001880-0785-11e9-9606-39aa3ce1ec14.png">
<img width="334" alt="small" src="https://user-images.githubusercontent.com/9882035/50400285-d198af00-0785-11e9-9153-830e3a62ee3a.png">
<img width="1328" alt="large" src="https://user-images.githubusercontent.com/9882035/50400286-d198af00-0785-11e9-9297-d6a254c6fdbd.png">
