### ISSUE TITLE
style guide

### ISSUE THREAD

**Issue by carne-vore** [SeMI-network/semi-website#237]
Bob - I have done the style guide 1.0 it is item 4 on the branding section of  http://dev.semi.network/service-manual/
and is at
http://dev.semi.network/service-manual/style-guide.html
can you give me feedback on it - and I want to make the glossary a similar page as item 5 - happy with that way of doing it (as a separate page)?

**Comment by bobvanluijt** [comment]
This is great @carne-vore! This is indeed the goal. Very happy, especially with the opening text.
