### ISSUE TITLE
Not all product logos are in the guide

### ISSUE THREAD

**Issue by bobvanluijt** [SeMI-network/semi-website#238]
Please add all logos to the styleguide: http://dev.semi.network/service-manual/style-graphic-products.html

**Comment by StudioSpindle** [comment]
Missing: 
- Semi networks
- Whitelabel platform

@rafaelcanalesduron could you check/update this list?
And if you're done and you're happy with the new layout, could you provide the SVG's in the same dimensions as the existing ones on that page?

**Comment by rafaelcanalesduron** [comment]
@StudioSpindle I updated the list of product logos. You can find them on this zeplin page:
web: https://zpl.io/a7Ek6Qp
app: zpl://screen?sid=5bb35ea01240df45cd3304bc&pid=5b7e6c6c20f52a2034f91e93 

The ones missing were Networks, White-Label, Keyper. Also those with the logotype/name changed. And for Consulting the version with the hexagon was removed. I guess it might be better to do a general update of all logos.

The way the products are organized is also slightly different than what we have, but I find it easier to browse through the different versions of the logos this way. Would it be possible to change that?
