### ISSUE TITLE
Consistent spacing between sections (add to manual)

### ISSUE THREAD

**Issue by rafaelcanalesduron** [SeMI-network/semi-website#241]
The spacing between sections in different parts of the website is not consistent. Giving it enough spacing creates some rhythm that allows for people to find and process information better.

@StudioSpindle Could we review this and define a set space that is consistent throughout the website? We need to add this also to the Service Manual. In Zeplin there is an indication of what that space would be.

Some examples:

Enough space between quote section and USPs section
![image](https://user-images.githubusercontent.com/41619961/51393287-9f396200-1b37-11e9-9976-aa4f00d46a70.png)

Not enough space between USP section and table; not enough space between title and table.
![image](https://user-images.githubusercontent.com/41619961/51393193-6c8f6980-1b37-11e9-9b52-4ca67d29af24.png)

Not enough space between description and first section:
![image](https://user-images.githubusercontent.com/41619961/51393149-4f5a9b00-1b37-11e9-8c90-0e3e5324e47f.png)

**Comment by StudioSpindle** [comment]
Add spacing page to service-manual.

**Comment by rafaelcanalesduron** [comment]
zpl://screen?sid=5b977b04d8b486047e4f61ea&pid=5b7e6c6c20f52a2034f91e93

**Comment by rafaelcanalesduron** [comment]
Maybe one of these:

web: https://zpl.io/2GOKzYr
app: zpl://screen?sid=5b977b04d8b486047e4f61ea&pid=5b7e6c6c20f52a2034f91e93

**Comment by StudioSpindle** [comment]
@rafaelcanalesduron added this page:

![screencapture-localhost-4000-service-manual-style-spacing-html-2019-02-01-15_53_49](https://user-images.githubusercontent.com/9882035/52130123-a4b7a180-2639-11e9-9196-1bc922a61cb9.png)
