### ISSUE TITLE
Weaviate missing in the title of Products and Services section.

### ISSUE THREAD

**Issue by rafaelcanalesduron** [SeMI-network/semi-website#243]
@carne-vore The title of products and services now reads as:

"W, The Decentralized Knowledge Graph"
![image](https://user-images.githubusercontent.com/41619961/51670470-f66f8480-1fc6-11e9-8d3a-a8e4272d7914.png)

I would suggest changing the title to read "Weaviate, The decentralized Knowledge Graph" to make it more clear.
![image](https://user-images.githubusercontent.com/41619961/51670442-e8b9ff00-1fc6-11e9-9b73-df2b01e5e671.png)

I'm not sure if this was done for SEO reasons, in which case I would suggest to use a logo with logotype.
![image](https://user-images.githubusercontent.com/41619961/51671757-ff158a00-1fc9-11e9-97af-1b4a238c91c4.png)

**Comment by carne-vore** [comment]
@rafaelcanalesduron good point - I agree it needs the name there - @StudioSpindle  what do you think - I like the look of the name in the logotype but can't comment on if that is the sensible thing for SEO - the name is written on the page at least 3 times so I assume that is enough?

**Comment by StudioSpindle** [comment]
That can be done. What is the text that you'd like to give more weight SEO wise? "The Decentralized Knowledge Graph" right?

I can make that sentence a h1 (more SEO value) and the logotype just a <span>, and give them the correct styling class.

What do you think @carne-vore ?

**Comment by carne-vore** [comment]
yes and no :) it is important to have the text  "The Decentralized Knowledge Graph" in SEO but equally important to have the name "Weaviate" but that is in the image - is there a way to ensure it gets the same SEO empahisis (snap je wat ik bedoel?)

**Comment by rafaelcanalesduron** [comment]
We could use as a title tag "The Decentralized Knowledge Graph | Weaviate", keep "The Decentralized Knowledge Graph" with the h1 tag, and use the logo with logotype there.
![image](https://user-images.githubusercontent.com/41619961/52113769-8d14f480-260a-11e9-8cfc-597772e5f466.png)

The title tag has more SEO value and we include the main keyworkds, plus the Weaviate brand. And for usability of the website, visitors can see we are referring to Weaviate when we say decentralized knowledge graph through the logo.

**Comment by carne-vore** [comment]
Good plan - I like that solution
