### ISSUE TITLE
Replace bullet points in Weaviate White Label page for USP items

### ISSUE THREAD

**Issue by rafaelcanalesduron** [SeMI-network/semi-website#250]
The bullet points in the intro of the White Label page does not fit the format and the content is somehow redundant to what we show below as USPs with graphics.
![image](https://user-images.githubusercontent.com/41619961/52120241-f8b38d80-261b-11e9-8892-b1a4e88ef898.png)

@carne-vore What do you think of merging those bullet points with the list of USPs?
![image](https://user-images.githubusercontent.com/41619961/52120392-711a4e80-261c-11e9-923a-c67c19d3d299.png)

**USP 1**
"Create custom Contextionaries for you" + "Work with your own team to add in whatever customizations you need". These two are quite similar, we could make one single USP referring to that it is fully customizable and mention contextionaries.

**USP 2**
"Provide you with monetization tools to generate revenue with your Weaviate". We already mention "Monetize your data" as a USP.

**USP 3**
"Provide an SLA, large scale deployment in your own cloud or on-premise". Here we could emphasize that you are in control of where to deploy.

**USP 4**
About support. We could merge it with the item mentioning help from consultants as one of the types of support, and also move the SLA bit to here since it also touches on support.

**USP 5**
Predefined Data Networks.

The one about Weaviate Enterprise is not very clear. Maybe changing the title to "Access to all the W Enterprise Features" and then mention what they are.

**Comment by carne-vore** [comment]
The language could be tighter (actually a centered bulleted list is a but weird - left aligned might be better - or no bullets). I'm concerned that people will not read below the fold - we do repeat the bulleted section more or less in the section below - would you put in the 5 USPs and remove the rest?

**Comment by rafaelcanalesduron** [comment]
Yes, what I meant is to have those 5 USPs instead of the bullet points and the USPs that are there now.

I agree with the quote. We could either remove it or just place it below after the feature table, so then as you say the 5 USps are at the top of the page.

**Comment by carne-vore** [comment]
Let's remove David - we are going to make a user stories page anyway

OK  so here is my proposal for the text
----------------
The white-label Platform version is based on the Weaviate Enterprise software and contains everything you need to run a full-blown, scalable-platform business with the push of a button:

A powerful platform to offer knowledge graph services to your customers

USP 1
Customization: we can create custom Contextionaries for you and work with your own team to add in whatever other enhancements you want.

USP 2
"Provide you with monetization tools to generate revenue with your Weaviate".

USP 3
We allow large scale deployment in your own cloud or on-premise, you can choose where to deploy your Weaviate.

USP 4
Support: we provide an SLA and have business consultants and data scientists to help you achieve your goals with Weaviate. Learn more about what SeMI consultants can do for you.

USP 5
Predefined Data Networks.

-----------------
It needs a bit of tweaking for wording and adding in the right links - but do you think this is now better. We only have 4 images - can you/remi come up with a 5th?

**Comment by StudioSpindle** [comment]
@rafaelcanalesduron creates the visual layout for this, then assignes this to me

**Comment by rafaelcanalesduron** [comment]
@carne-vore Check out the layout and content: https://zpl.io/am9z6ZK
I tweaked the text so that they all are presented in the same way: the usp in one sentence, a description explaining how.

If it's ok @StudioSpindle can start modifying the page.

**Comment by carne-vore** [comment]
Hi - looks good - yes, lets go with this - thx
