### ISSUE TITLE
New SeMI Logos in Service Manual

### ISSUE THREAD

**Issue by rafaelcanalesduron** [SeMI-network/semi-website#251]
We have developed a new SeMI logo and a set of different variations for it.
These are in Zeplin:
web: zpl.io/bWgroJx
app: zpl://screen?pid=5b7e6c6c20f52a2034f91e93&sid=5c59a5e498ba974304641b40 

We should also update the content for this page. The text is in this doc:
https://docs.google.com/document/d/1LRYupcCPUI6ulh1r7TmYZAHobyIxaWdWmnL7IPvZx1g/

These logos should be able to be downloaded as PNGs and SVGs.
@StudioSpindle What would you recommend to do in order to be able to use them?
Currently we have one link for SVG and PNG. Would it be useful for you as a front end developer to have for example a code snippet to copy paste, download them individually, or get them all in a zip?

I was looking at references of how others organize graphical assets:
https://www.audi.com/ci/en/guides/user-interface/icon-library.html? 
https://design.axa.com/web-guidelines/logo 
https://atlassian.design/guidelines/marketing/resources/logo-files

Which of these approaches seems more usable from your perspective?

**Comment by StudioSpindle** [comment]
Thanks for the suggestion. Added them as a .zip just as you stated. In that I could add the png's for different screen resolutions so developers have all the resources that they need.

I took the liberty to adjust the layout a bit. In this setup the logo's are both normal and inverted in each view. That makes it easy to select one or another. Let me know what you think.

**Comment by StudioSpindle** [comment]
see it here:
[service-manual-logo-page.pdf](https://github.com/SeMI-network/semi-website/files/2840137/service-manual-logo-page.pdf)

**Comment by rafaelcanalesduron** [comment]
@StudioSpindle The layout works pretty well. Let's use that.

I have a few remarks:

- Can you also add the monochromatic versions in white and in black? Create a section called "Monochrome Logo", with the Black version on the left, the white one on the right. Description: "Use the monochrome versions when the format requires you to apply the logo in a single color."

- The logomark on dark background misses the download links.

- Also remove the "Logo Accents" title and the paragraph about contrasting images, and make this part of the "Logo" section.

- And remove the title "Horizontal Logo with Payoff" and make these two part of the "Full logo with payoff" section.

**Comment by StudioSpindle** [comment]
Yes, did them except for one: The logo mark on the dark background is the same as on the left without the dark background. It's just displayed on a dark background.

**Comment by StudioSpindle** [comment]
[logo-page-with-chromo-logos.pdf](https://github.com/SeMI-network/semi-website/files/2841884/logo-page-with-chromo-logos.pdf)

**Comment by rafaelcanalesduron** [comment]
@StudioSpindle You're right!, they are the same! 😅I saw an empty space there and felt like something was missing.
All seems to be there. Thanks!

When will it be in the dev and production sites?
