### ISSUE TITLE
Update SeMI site with new logo

### ISSUE THREAD

**Issue by rafaelcanalesduron** [SeMI-network/semi-website#252]
The logo is currently used only in the navigation bar of different pages. Depending on the background there are variations of the logo used.

Dark backgrounds: the full horizontal white-accent version.
![image](https://user-images.githubusercontent.com/41619961/52331409-67b42c00-29f8-11e9-8478-19594624c949.png)
Zeplin web: https://zpl.io/29o6qAl
app: zpl://screen?pid=5b7e6c6c20f52a2034f91e93&sid=5b977b07bdcd998f8b93b0c5

Light backgrounds: full horizontal color version.
![image](https://user-images.githubusercontent.com/41619961/52331589-d98c7580-29f8-11e9-9c0f-bf3f33eb6a3b.png)
Zeplin web: https://zpl.io/agNYGLA
app: zpl://screen?pid=5b7e6c6c20f52a2034f91e93&sid=5c5aa34d4e189735594ac0f7

@StudioSpindle Can you update them?

**Comment by StudioSpindle** [comment]
is picked up in #251, will close this one and work in 251
