### ISSUE TITLE
Create dedicated sub page for Open source product as subpage of products

### ISSUE THREAD

**Issue by carne-vore** [SeMI-network/semi-website#255]
make this one a minimal page as this will be mostly pushing user to github

**Comment by rafaelcanalesduron** [comment]
@carne-vore you are providing the content first, right?

**Comment by carne-vore** [comment]
I would say leave just the bold stuff in the products page box - I think I will tweak the language a tiny bit later.
On the subpage (is there a proper word for subpage?) itself we will need a logo at the top and the name like on the enterprise page.

The Decentralized Knowledge Graph

The Open Source version of Weavciate consists of our powerful knowledge graph software in GitHub. You can use the supplied Contextionary (which we continuously upgrade so your experience improves). You can use your own team to work with the software and start deploying use cases right away. You can create a peer-to-peer network of multiple weaviates. The online playground is also there for data analysis.

[Playground image and paragraph]

[Features table]

Reach out txt and contact us button

**Comment by rafaelcanalesduron** [comment]
Added a reference page in zeplin: https://zpl.io/2vKzjzJ
@carne-vore I have some suggestions on your latest commit: 
- We should still have an introduction to Weaviate Open Source, just one or two sentences summarizing what it is and why is it valuable.
- On peer to peer networks, we should mention what is the value of having p2p networks in Weaviate. What do they enable customers to achieve?

**Comment by rafaelcanalesduron** [comment]
@carne-vore on content, the peer-to-peer network point is still missing why it matter. See my previous comment.

> On peer to peer networks, we should mention what is the value of having p2p networks in Weaviate. What do they enable customers to achieve?


@StudioSpindle I would like to add a standout/call to action component with a dark background for the CTA to go to Github as in the design document https://zpl.io/2vKzjzJ

**Comment by carne-vore** [comment]
I like the CTA - good - who will add that in? (I don't know how :)
I have done the peer-to-peer purpose and pushed it back
