### ISSUE TITLE
Product overview page with core products, add-ons and point solutions

### ISSUE THREAD

**Issue by rafaelcanalesduron** [SeMI-network/semi-website#259]
The current product page is too complex.
New setup: core products, addons and point solutions.
![image](https://user-images.githubusercontent.com/41619961/52553118-da4f4e00-2de2-11e9-9dfc-382e918731dc.png)

**Comment by rafaelcanalesduron** [comment]
Zeplin reference: https://zpl.io/agNYGLA
@carne-vore are you creating the content for this page?

**Comment by StudioSpindle** [comment]
Add card to "Add ons"
Add three cards to "Point solutions". Hide them in a code comment.

**Comment by StudioSpindle** [comment]
links to #261

**Comment by StudioSpindle** [comment]
TODO: Add titles, add excerpts to: add on tile keyper, point solution tiles.

**Comment by carne-vore** [comment]
I have pushed a point solutions mockup to the product_pages brnach - how do I get the spacing tighter and alignment left on these headings?
![image](https://user-images.githubusercontent.com/45226724/52699717-b7ee3980-2f76-11e9-9da7-811841b18f19.png)

**Comment by rafaelcanalesduron** [comment]
@carne-vore for layout / style, use the zeplin doc as a reference.
- Leave the headings and paragraphs centered.
- The description format is not the right one. I see you are using some version of h2, it should be the paragraph default.
- It was decided to remove the weaviate logo at the top and add a title for the page (e.g. Products and Services, or something else you consider more appropriate) and three sections with headings: Core Products, Add-ons, Point Solutions. We ar emissing the Core Products section: a heading + description. 
- I agree, the vertical spacing between components/sections should be consistent with the rest of the website. @StudioSpindle how do we fix this?

**Comment by carne-vore** [comment]
I'm not really able to do anything with the spacing I hope @StudioSpindle  can help - the rest I have done and pushed to the branch

**Comment by carne-vore** [comment]
After review with @rafaelcanalesduron  today here are the outstanding items for these pages
Main page and designs
1 @StudioSpindle will you look at the spacing there is often too much between the headings and the things below
2 is it possible to make the middots bigger between the 3 elements of W "Knowledge graphs • AI-based contextuality • Decentralized networks"
3 is core products the right name @carne-vore to ask Bob (done - waiting on answer)
4 Analytics - can we add hotjar to the pages for the go-live and do some analysis - make new snapshot
5 @StudioSpindle on different machines the pages align differently - on my windows box the add ons and points stretch to fulll width and are centered - for @rafaelcanalesduron  they don't stretch and are left aligned - they should be centered and not stretch
6 Point solutions - how do we control the colours of the various boxes @StudioSpindle ? @rafaelcanalesduron will also think about branding here
7 on windows the cookie accept box is showing weird symbols 
![image](https://user-images.githubusercontent.com/45226724/52855631-4652ee80-3122-11e9-915a-061070cdb7d9.png)
8 Add CTA for github link on Open Source page @StudioSpindle 
9 add black box as highlight around the product shown on the 3 product sub pages - @StudioSpindle 
10 we need to consistently show the isometric background on each page as it is on the products page - it is missing from OS, networks and consulting - also it appears as a blob on top left in chrome/windows but correctly as a background on firefox/windows - sorry @StudioSpindle  another one for you

with all these things resolved we should be able to go live

**Comment by rafaelcanalesduron** [comment]
About point 5 of the previous comment:
![image](https://user-images.githubusercontent.com/41619961/52848914-33372300-3110-11e9-87cc-bd2531258b06.png)
![image](https://user-images.githubusercontent.com/41619961/52848970-51048800-3110-11e9-94f1-d375a216099f.png)

**Comment by StudioSpindle** [comment]
TODO: 1, 5, 7, 8, 10 (see above) 18-02-2019

**Comment by StudioSpindle** [comment]
@carne-vore above points fixed. Can be re-tested to make sure they're fixed (especially the windows bugs)

**Comment by carne-vore** [comment]
Thx Remi, great job getting thrm done so fast, will test first thing tomorrow (weds)


J




Outlook voor Android downloaden







On Mon, Feb 18, 2019 at 10:07 PM +0100, "Remi Vledder" <notifications@github.com> wrote:












@carne-vore above points fixed. Can be re-tested to make sure they're fixed (especially the windows bugs)
