### ISSUE TITLE
Create R&D or "in development" label for cards (to indicate under construction)

### ISSUE THREAD

**Issue by StudioSpindle** [SeMI-network/semi-website#261]

**Comment by StudioSpindle** [comment]
@rafaelcanalesduron can you let me know if you have a design I can add as an option to the cards?

**Comment by rafaelcanalesduron** [comment]
See the reference here: https://zpl.io/agNYGLA
The cards for point solutions with 'in development' products, have no buttons and a tag next to the logo with the legend "In Development". The logos in the zeplin file for now are placeholders, we don't know what point solutions will be there yet and the plan is to have new logos for each of these point solutions.

**Comment by StudioSpindle** [comment]
It's in the product pages branch. Closing this issue.
