### ISSUE TITLE
background mesh on pages doesn't render properly

### ISSUE THREAD

**Issue by carne-vore** [SeMI-network/semi-website#289]
the isometric mesh on the pages renders oddly in the top left corner of the pages (in firefox, edge and chrome on windows at least) 
![afbeelding](https://user-images.githubusercontent.com/45226724/53159406-1c884480-35c6-11e9-8b42-dedf3b219d42.png)

it should spread across the whole page I think

**Comment by StudioSpindle** [comment]
I think that's the desired result. As by design in Zeplin. Example: 

<img width="789" alt="screenshot 2019-02-28 at 09 56 18" src="https://user-images.githubusercontent.com/9882035/53554054-33d3ae80-3b3f-11e9-84de-98c5fd622c05.png">

**Comment by carne-vore** [comment]
Oh - OK I will close this then
